### ISSUE TITLE
NAS Drive troulbeshooting

### ISSUE THREAD

**Issue by aavanaham** [noolahamfoundation/organization#65]
நூலகத்தில் NAS Drive ஒன்று பயன்படுத்தப்படுகிறது.  அதன் beeping சத்தம் தொடர்ந்து போடுவதாகக் கூறப்படுகிறது.  அதற்கான காரணத்தை அறிந்து, அது எதாவது problem ஐ indicate செய்கிறதா என்று பார்க்க வேண்டும்.

சோமராஜ் சிக்கலை மேலும் விபரிப்பார்.  சுபாவிடம் அணுக்கம் பெறலாம்.

**Comment by kayankayanthan** [comment]
நான் இன்று NAS பற்றி பார்த்தேன். அங்கு சில hard disk செயல்படவில்லை (234) அத்துடன் அதன் backup செயல்பாடு செயல்படவில்லை.இபோது நான் அதை reset செய்துளேன். அதன் backup hard disk ஐ மீண்டும் format செய்யவேண்டியுள்ளது .அதை  இபோது தட்காலிகமாக beep சத்தத்தை நிறுத்திஉளேன்.அதை உடனடியாக சரிசெய்யவேண்டும் .

**Comment by Parathantl** [comment]
NAS Drive is reset and configured to take regular backup everyday. A Documentation was prepared by me to reset and configure backup scheduling for future use. 

Pls find the following Goolge DOC link for the Documentation.

https://docs.google.com/document/d/1imU0vLGSj6Jxc8do4IylwF-bDFfBjgeBaNqu0Xx4TMM/edit?usp=sharing
